// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmahszizIBCxbGVxQ-5zh0kLjg-xAX67U',
    appId: '1:655032531508:web:d745f3f56b1123a44a6861',
    messagingSenderId: '655032531508',
    projectId: 'end-of-sem-56a6e',
    authDomain: 'end-of-sem-56a6e.firebaseapp.com',
    storageBucket: 'end-of-sem-56a6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9TMrOfu2NhIp3mB1HhpPkL2iHITuAvC8',
    appId: '1:655032531508:android:9e2010b1da4281694a6861',
    messagingSenderId: '655032531508',
    projectId: 'end-of-sem-56a6e',
    storageBucket: 'end-of-sem-56a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwNA2HEuzvkQnYjbhw28m3N302ZRRkDU',
    appId: '1:655032531508:ios:01457ac0e29b151a4a6861',
    messagingSenderId: '655032531508',
    projectId: 'end-of-sem-56a6e',
    storageBucket: 'end-of-sem-56a6e.firebasestorage.app',
    iosBundleId: 'com.example.endOfSem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwNA2HEuzvkQnYjbhw28m3N302ZRRkDU',
    appId: '1:655032531508:ios:01457ac0e29b151a4a6861',
    messagingSenderId: '655032531508',
    projectId: 'end-of-sem-56a6e',
    storageBucket: 'end-of-sem-56a6e.firebasestorage.app',
    iosBundleId: 'com.example.endOfSem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmahszizIBCxbGVxQ-5zh0kLjg-xAX67U',
    appId: '1:655032531508:web:a356ed1b09ae46d94a6861',
    messagingSenderId: '655032531508',
    projectId: 'end-of-sem-56a6e',
    authDomain: 'end-of-sem-56a6e.firebaseapp.com',
    storageBucket: 'end-of-sem-56a6e.firebasestorage.app',
  );
}
